---
title: "How to write Code components in PsychoPy"
author: "Matt Green"
format: html
editor: source
date: now
date-format: DD MMMM, YYYY, HH:mm:ss
toc: true
license: "CC BY-NC-SA"
---

## About

This material lives at a [repository on github](https://github.com/mjgreen/coding-psychopy-2024){target="_blank"}.

This long-form content is at [this link](https://mjgreen.github.io/coding-psychopy-2024/){target="_blank"}.

There are slides at [this link](https://mjgreen.github.io/coding-psychopy-2024/slides.html){target="_blank"}.

## Check out

[Getting started with Code Components in PsychoPy (by making a visual search task!](https://youtu.be/0dJgLf7BxbE)

## Intro

***The Builder, python, and javascript***

PsychoPy has a Builder interface that allows you to specify an experiment using a visual icon-based interface. It is still possible to write raw python code that calls the psychopy libraries - this is how psychopy started life, as a set of routines that simplified doing repetitive tasks in python like creating shapes and drawing them to the screen.

The Builder takes your visual representation of the experiment and translates it into those low-level python routines.

In response to Covid and the associated requirement to deploy experiments that can be carried out online via web browsers, the Builder can now generate javascript equivalents of those low-level python routines. Using javascript for this is not a choice - we are constrained to use javascript because that is the language of the web browser. 

So the Builder is the starting point and python and javascript are the two output options.

For anything beyond basic stimulus response, we have to go beyond the basic Builder icons for things like "image" and write raw python which we inject using the "Code" icon.

For psychologists who know a little python, this can result in a fairly complex experiment that runs in a lab. To meet the need to run complex experiments online, without requiring users to learn javascript, there is an ongoing "auto-translation" effort that works one-way `python -> javascript`. 

This is ok, but it can be difficult to establish that the resulting javascript does what you want; and the auto-translation feature is incomplete, so inevitably you have to learn a little javascript if you want to deploy complex experiments online.

## Randomisation

Simple randomisation is handled by shuffling the spreadsheet that controls a loop. This works for presenting pre-defined trial contents in a different order for each participant.

An example of a situation where randomising in code would be useful is ...

::: {.callout-note}
## Randomisation Example
Insert Tara's face-grid experiment
:::

## Flow control 

Any time you want to say **if... then... else**, the name of the programming feature you want is **flow control**.

## Previous responses

Previous responses can be accessed in PsychoPy -- you just need to know the conventions used for naming the various parts of the experiment. For example if you have a keyboard component called *response* and the participant responded by pressing the key "a", then you can access the "a" by using the name `response.resp`. In programming the term **key-value pair** is used for this relationship -- we refer to `response.resp` as the **key** and we refer to "a" as the **value**.

## Callout blocks {.appendix}

::: {.callout-note}
Note that there are five types of callouts, including:
`note`, `warning`, `important`, `tip`, and `caution`.
:::
